// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reimbit.Infrastructure.Data;

#nullable disable

namespace Reimbit.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Reimbit.Domain.Models.ComExpenseQuery", b =>
                {
                    b.Property<int>("QueryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("QueryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QueryId"));

                    b.Property<int>("ExpenseId")
                        .HasColumnType("int")
                        .HasColumnName("ExpenseID");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("SenderUserId")
                        .HasColumnType("int")
                        .HasColumnName("SenderUserID");

                    b.Property<DateTime?>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("([dbo].[GETServerDateTime]())");

                    b.HasKey("QueryId")
                        .HasName("PK__COM_Expe__5967F7FBBC815B6A");

                    b.HasIndex("ExpenseId");

                    b.HasIndex("SenderUserId");

                    b.ToTable("COM_ExpenseQuery", (string)null);
                });

            modelBuilder.Entity("Reimbit.Domain.Models.ExpCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("CreatedByUserID");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("Modified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("([dbo].[GETServerDateTime]())");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("ModifiedByUserID");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("OrganizationID");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("ProjectID");

                    b.HasKey("CategoryId")
                        .HasName("PK__EXP_Cate__19093A2B34B6A9B7");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ProjectId");

                    b.ToTable("EXP_Category", (string)null);
                });

            modelBuilder.Entity("Reimbit.Domain.Models.ExpExpense", b =>
                {
                    b.Property<int>("ExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ExpenseID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExpenseId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<string>("AttachmentUrl")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("CreatedByUserID");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("INR");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpenseStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("submitted");

                    b.Property<DateTime>("Modified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("([dbo].[GETServerDateTime]())");

                    b.Property<int>("ModifiedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("ModifiedByUserID");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("OrganizationID");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("ProjectID");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("ExpenseId")
                        .HasName("PK__EXP_Expe__1445CFF34223D76F");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("EXP_Expense", (string)null);
                });

            modelBuilder.Entity("Reimbit.Domain.Models.ExpReport", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReportID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<decimal>("AcceptedAmount")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("CreatedByUserID");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int")
                        .HasColumnName("ManagerID");

                    b.Property<DateTime>("Modified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("([dbo].[GETServerDateTime]())");

                    b.Property<int>("ModifiedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("ModifiedByUserID");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("OrganizationID");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("ProjectID");

                    b.Property<decimal>("RejectedAmount")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<string>("ReportStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("submitted");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("ViewedAt")
                        .HasColumnType("datetime");

                    b.HasKey("ReportId")
                        .HasName("PK__EXP_Repo__D5BD48E52D8C23FB");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ProjectId");

                    b.ToTable("EXP_Report", (string)null);
                });

            modelBuilder.Entity("Reimbit.Domain.Models.LogComExpenseQuery", b =>
                {
                    b.Property<int>("LogexpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LOGExpenseID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogexpenseId"));

                    b.Property<int?>("ExpenseId")
                        .HasColumnType("int")
                        .HasColumnName("ExpenseID");

                    b.Property<bool?>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Iud")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("IUD")
                        .IsFixedLength();

                    b.Property<int>("IudbyUserId")
                        .HasColumnType("int")
                        .HasColumnName("IUDByUserID");

                    b.Property<DateTime>("IuddateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("IUDDateTime");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("QueryId")
                        .HasColumnType("int")
                        .HasColumnName("QueryID");

                    b.Property<int?>("SenderUserId")
                        .HasColumnType("int")
                        .HasColumnName("SenderUserID");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime");

                    b.HasKey("LogexpenseId")
                        .HasName("PK__LOG_COM___1396EC433B74A47F");

                    b.ToTable("LOG_COM_ExpenseQuery", (string)null);
                });

            modelBuilder.Entity("Reimbit.Domain.Models.LogErrorDbm", b =>
                {
                    b.Property<int>("ErrorDbmsid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ErrorDBMSID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ErrorDbmsid"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<int?>("ErrorLine")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("ErrorNumber")
                        .HasColumnType("int");

                    b.Property<string>("ErrorProcedure")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("ErrorSeverity")
                        .HasColumnType("int");

                    b.Property<int?>("ErrorState")
                        .HasColumnType("int");

                    b.Property<bool?>("IsSolved")
                        .HasColumnType("bit");

                    b.Property<string>("Spdetail")
                        .HasMaxLength(4000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4000)")
                        .HasColumnName("SPDetail");

                    b.Property<DateTime?>("VerifiedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("VerifiedRemarks")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("ErrorDbmsid")
                        .HasName("PK__LOG_Erro__C97849796A38A933");

                    b.ToTable("LOG_ErrorDBMS", (string)null);
                });

            modelBuilder.Entity("Reimbit.Domain.Models.LogExpCategory", b =>
                {
                    b.Property<int>("LogcategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LOGCategoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogcategoryId"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("CreatedByUserID");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Iud")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("IUD")
                        .IsFixedLength();

                    b.Property<int>("IudbyUserId")
                        .HasColumnType("int")
                        .HasColumnName("IUDByUserID");

                    b.Property<DateTime>("IuddateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("IUDDateTime");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("ModifiedByUserID");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("OrganizationID");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("ProjectID");

                    b.HasKey("LogcategoryId")
                        .HasName("PK__LOG_EXP___826DC51EFF8B6848");

                    b.ToTable("LOG_EXP_Category", (string)null);
                });

            modelBuilder.Entity("Reimbit.Domain.Models.LogExpExpense", b =>
                {
                    b.Property<int>("LogexpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LOGExpenseID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogexpenseId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<string>("AttachmentUrl")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("CreatedByUserID");

                    b.Property<string>("Currency")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExpenseId")
                        .HasColumnType("int")
                        .HasColumnName("ExpenseID");

                    b.Property<string>("ExpenseStatus")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Iud")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("IUD")
                        .IsFixedLength();

                    b.Property<int>("IudbyUserId")
                        .HasColumnType("int")
                        .HasColumnName("IUDByUserID");

                    b.Property<DateTime>("IuddateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("IUDDateTime");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("ModifiedByUserID");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("OrganizationID");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("ProjectID");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("LogexpenseId")
                        .HasName("PK__LOG_EXP___1396EC43F90D78B8");

                    b.ToTable("LOG_EXP_Expense", (string)null);
                });

            modelBuilder.Entity("Reimbit.Domain.Models.LogExpReport", b =>
                {
                    b.Property<int>("LogorganizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LOGOrganizationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogorganizationId"));

                    b.Property<decimal?>("AcceptedAmount")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("CreatedByUserID");

                    b.Property<string>("Iud")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("IUD")
                        .IsFixedLength();

                    b.Property<int>("IudbyUserId")
                        .HasColumnType("int")
                        .HasColumnName("IUDByUserID");

                    b.Property<DateTime>("IuddateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("IUDDateTime");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int")
                        .HasColumnName("ManagerID");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("ModifiedByUserID");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("OrganizationID");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("ProjectID");

                    b.Property<decimal?>("RejectedAmount")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<int?>("ReportId")
                        .HasColumnType("int")
                        .HasColumnName("ReportID");

                    b.Property<string>("ReportStatus")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Title")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("ViewedAt")
                        .HasColumnType("datetime");

                    b.HasKey("LogorganizationId")
                        .HasName("PK__LOG_EXP___069D042F58DD22DF");

                    b.ToTable("LOG_EXP_Report", (string)null);
                });

            modelBuilder.Entity("Reimbit.Domain.Models.LogOrgOrganization", b =>
                {
                    b.Property<int>("LogorganizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LOGOrganizationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogorganizationId"));

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("Iud")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("IUD")
                        .IsFixedLength();

                    b.Property<int>("IudbyUserId")
                        .HasColumnType("int")
                        .HasColumnName("IUDByUserID");

                    b.Property<DateTime>("IuddateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("IUDDateTime");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("OrganizationID");

                    b.Property<string>("OrganizationName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LogorganizationId")
                        .HasName("PK__LOG_ORG___069D042F86518407");

                    b.ToTable("LOG_ORG_Organization", (string)null);
                });

            modelBuilder.Entity("Reimbit.Domain.Models.LogProjProject", b =>
                {
                    b.Property<int>("LogprojectsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LOGProjectsID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogprojectsId"));

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("CreatedByUserID");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Iud")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("IUD")
                        .IsFixedLength();

                    b.Property<int>("IudbyUserId")
                        .HasColumnType("int")
                        .HasColumnName("IUDByUserID");

                    b.Property<DateTime>("IuddateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("IUDDateTime");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int")
                        .HasColumnName("ManagerID");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("ModifiedByUserID");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("OrganizationID");

                    b.Property<string>("ProjectDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProjectDetails")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("ProjectID");

                    b.Property<string>("ProjectLogoUrl")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ProjectName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("LogprojectsId")
                        .HasName("PK__LOG_PROJ__FFB6CA576D4F012F");

                    b.ToTable("LOG_PROJ_Project", (string)null);
                });

            modelBuilder.Entity("Reimbit.Domain.Models.LogProjProjectMember", b =>
                {
                    b.Property<int>("LogprojectMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LOGProjectMemberID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogprojectMemberId"));

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("Iud")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("IUD")
                        .IsFixedLength();

                    b.Property<int>("IudbyUserId")
                        .HasColumnType("int")
                        .HasColumnName("IUDByUserID");

                    b.Property<DateTime>("IuddateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("IUDDateTime");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("OrganizationID");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("LogprojectMemberId")
                        .HasName("PK__LOG_PROJ__73616FE1CC96DD33");

                    b.ToTable("LOG_PROJ_ProjectMember", (string)null);
                });

            modelBuilder.Entity("Reimbit.Domain.Models.LogSecRoleClaim", b =>
                {
                    b.Property<int>("LogorganizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LOGOrganizationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogorganizationId"));

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("CreatedByUserID");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Iud")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("IUD")
                        .IsFixedLength();

                    b.Property<int>("IudbyUserId")
                        .HasColumnType("int")
                        .HasColumnName("IUDByUserID");

                    b.Property<DateTime>("IuddateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("IUDDateTime");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("ModifiedByUserID");

                    b.Property<int?>("RoleClaimId")
                        .HasColumnType("int")
                        .HasColumnName("RoleClaimID");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.HasKey("LogorganizationId")
                        .HasName("PK__LOG_SEC___069D042FD03431A3");

                    b.ToTable("LOG_SEC_RoleClaim", (string)null);
                });

            modelBuilder.Entity("Reimbit.Domain.Models.LogSecUser", b =>
                {
                    b.Property<int>("LogUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LOGUserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogUserId"));

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("CreatedByUserID");

                    b.Property<string>("Email")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Iud")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("IUD")
                        .IsFixedLength();

                    b.Property<int>("IudbyUserId")
                        .HasColumnType("int")
                        .HasColumnName("IUDByUserID");

                    b.Property<DateTime>("IuddateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("IUDDateTime");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MobileNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("ModifiedByUserID");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<string>("UserName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UserProfileImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("LogUserId")
                        .HasName("PK__LOG_SEC___96549365657C309E");

                    b.ToTable("LOG_SEC_User", (string)null);
                });

            modelBuilder.Entity("Reimbit.Domain.Models.LogSecUserAuth", b =>
                {
                    b.Property<int>("LoguserAuthId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LOGUserAuthID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoguserAuthId"));

                    b.Property<string>("Iud")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("IUD")
                        .IsFixedLength();

                    b.Property<int>("IudbyUserId")
                        .HasColumnType("int")
                        .HasColumnName("IUDByUserID");

                    b.Property<DateTime>("IuddateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("IUDDateTime");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("OrganizationID");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("LoguserAuthId")
                        .HasName("PK__LOG_SEC___5AAC1518BAB4BDB6");

                    b.ToTable("LOG_SEC_UserAuth", (string)null);
                });

            modelBuilder.Entity("Reimbit.Domain.Models.LogSecUserRole", b =>
                {
                    b.Property<int>("LogorganizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LOGOrganizationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogorganizationId"));

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("CreatedByUserID");

                    b.Property<string>("Iud")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("IUD")
                        .IsFixedLength();

                    b.Property<int>("IudbyUserId")
                        .HasColumnType("int")
                        .HasColumnName("IUDByUserID");

                    b.Property<DateTime>("IuddateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("IUDDateTime");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("ModifiedByUserID");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<int?>("UserRoleId")
                        .HasColumnType("int")
                        .HasColumnName("UserRoleID");

                    b.HasKey("LogorganizationId")
                        .HasName("PK__LOG_SEC___069D042FC77CE1D9");

                    b.ToTable("LOG_SEC_UserRole", (string)null);
                });

            modelBuilder.Entity("Reimbit.Domain.Models.MstSpexecution", b =>
                {
                    b.Property<int>("SpexecutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SPExecutionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpexecutionId"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("ExecutionTimeMs")
                        .HasColumnType("int")
                        .HasColumnName("ExecutionTimeMS");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Spname")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("SPName");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("SpexecutionId")
                        .HasName("PK__MST_SPEx__78733736095011A3");

                    b.ToTable("MST_SPExecution", (string)null);
                });

            modelBuilder.Entity("Reimbit.Domain.Models.OrgOrganization", b =>
                {
                    b.Property<int>("OrganizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrganizationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrganizationId"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("CreatedByUserID");

                    b.Property<DateTime>("Modified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("([dbo].[GETServerDateTime]())");

                    b.Property<int>("ModifiedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("ModifiedByUserID");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("OrganizationId")
                        .HasName("PK__ORG_Orga__CADB0B722E44CF29");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex(new[] { "OrganizationName" }, "UQ__ORG_Orga__F50959E41C5632A3")
                        .IsUnique();

                    b.ToTable("ORG_Organization", (string)null);
                });

            modelBuilder.Entity("Reimbit.Domain.Models.ProjExpensePolicy", b =>
                {
                    b.Property<int>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PolicyID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolicyId"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    b.Property<DateTime?>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsReceiptMandatory")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MaxAmount")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("ProjectID");

                    b.HasKey("PolicyId")
                        .HasName("PK__PROJ_Exp__2E13394431904DD5");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProjectId");

                    b.ToTable("PROJ_ExpensePolicy", (string)null);
                });

            modelBuilder.Entity("Reimbit.Domain.Models.ProjProject", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProjectID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("CreatedByUserID");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("ManagerId")
                        .HasColumnType("int")
                        .HasColumnName("ManagerID");

                    b.Property<DateTime>("Modified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("([dbo].[GETServerDateTime]())");

                    b.Property<int>("ModifiedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("ModifiedByUserID");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("OrganizationID");

                    b.Property<string>("ProjectDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProjectDetails")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProjectLogoUrl")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("ProjectId")
                        .HasName("PK__PROJ_Pro__761ABED07EB7813A");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex(new[] { "ProjectName", "OrganizationId" }, "PROJ_Project_ORG")
                        .IsUnique();

                    b.ToTable("PROJ_Project", (string)null);
                });

            modelBuilder.Entity("Reimbit.Domain.Models.ProjProjectMember", b =>
                {
                    b.Property<int>("ProjectMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProjectMemberID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectMemberId"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Modified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("([dbo].[GETServerDateTime]())");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("OrganizationID");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("ProjectID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("ProjectMemberId")
                        .HasName("PK__PROJ_Pro__E4E9983C3384D229");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("PROJ_ProjectMember", (string)null);
                });

            modelBuilder.Entity("Reimbit.Domain.Models.SecOperation", b =>
                {
                    b.Property<int>("OperationId")
                        .HasColumnType("int")
                        .HasColumnName("OperationID");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("OperationName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("OperationNo")
                        .HasColumnType("int");

                    b.HasKey("OperationId")
                        .HasName("PK__SEC_Oper__A4F5FC6459503172");

                    b.ToTable("SEC_Operation", (string)null);
                });

            modelBuilder.Entity("Reimbit.Domain.Models.SecRole", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("CreatedByUserID");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("Modified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("([dbo].[GETServerDateTime]())");

                    b.Property<int>("ModifiedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("ModifiedByUserID");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("OrganizationID");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__SEC_Role__8AFACE3A5F88263D");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex(new[] { "OrganizationId", "RoleName" }, "UK_SEC_Role_Org_Name")
                        .IsUnique()
                        .HasFilter("[OrganizationID] IS NOT NULL");

                    b.ToTable("SEC_Role", (string)null);
                });

            modelBuilder.Entity("Reimbit.Domain.Models.SecRoleClaim", b =>
                {
                    b.Property<int>("RoleClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleClaimID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleClaimId"));

                    b.Property<string>("ClaimValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ClaminType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("CreatedByUserID");

                    b.Property<DateTime>("Modified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("([dbo].[GETServerDateTime]())");

                    b.Property<int>("ModifiedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("ModifiedByUserID");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.HasKey("RoleClaimId")
                        .HasName("PK__SEC_Role__BB90E97636D64882");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("RoleId");

                    b.ToTable("SEC_RoleClaim", (string)null);
                });

            modelBuilder.Entity("Reimbit.Domain.Models.SecUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("CreatedByUserID");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MobileNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Modified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("([dbo].[GETServerDateTime]())");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("ModifiedByUserID");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UserProfileImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("UserId")
                        .HasName("PK__SEC_User__1788CCAC69E512E5");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex(new[] { "Email" }, "UQ__SEC_User__08638DF858550AC5")
                        .IsUnique();

                    b.HasIndex(new[] { "MobileNo" }, "UQ__SEC_User__1D6F012637269705")
                        .IsUnique()
                        .HasFilter("[MobileNo] IS NOT NULL");

                    b.ToTable("SEC_User", (string)null);
                });

            modelBuilder.Entity("Reimbit.Domain.Models.SecUserAuth", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("OrganizationID");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("RefreshTokenExpiry")
                        .HasColumnType("datetime");

                    b.HasKey("UserId")
                        .HasName("PK__SEC_User__1788CCACC0680279");

                    b.HasIndex("OrganizationId");

                    b.ToTable("SEC_UserAuth", (string)null);
                });

            modelBuilder.Entity("Reimbit.Domain.Models.SecUserRole", b =>
                {
                    b.Property<int>("UserRoleId")
                        .HasColumnType("int")
                        .HasColumnName("UserRoleID");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("CreatedByUserID");

                    b.Property<DateTime>("Modified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("([dbo].[GETServerDateTime]())");

                    b.Property<int>("ModifiedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("ModifiedByUserID");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("UserRoleId")
                        .HasName("PK__SEC_User__3D978A55BD9594BD");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("UserId");

                    b.ToTable("SEC_UserRole", (string)null);
                });

            modelBuilder.Entity("Reimbit.Domain.Models.ComExpenseQuery", b =>
                {
                    b.HasOne("Reimbit.Domain.Models.ExpExpense", "Expense")
                        .WithMany("ComExpenseQueries")
                        .HasForeignKey("ExpenseId")
                        .IsRequired()
                        .HasConstraintName("FK__COM_Expen__Expen__3864608B");

                    b.HasOne("Reimbit.Domain.Models.SecUser", "SenderUser")
                        .WithMany("ComExpenseQueries")
                        .HasForeignKey("SenderUserId")
                        .IsRequired()
                        .HasConstraintName("FK__COM_Expen__Sende__395884C4");

                    b.Navigation("Expense");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("Reimbit.Domain.Models.ExpCategory", b =>
                {
                    b.HasOne("Reimbit.Domain.Models.SecUser", "CreatedByUser")
                        .WithMany("ExpCategoryCreatedByUsers")
                        .HasForeignKey("CreatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK__EXP_Categ__Creat__1F98B2C1");

                    b.HasOne("Reimbit.Domain.Models.SecUser", "ModifiedByUser")
                        .WithMany("ExpCategoryModifiedByUsers")
                        .HasForeignKey("ModifiedByUserId")
                        .HasConstraintName("FK__EXP_Categ__Modif__208CD6FA");

                    b.HasOne("Reimbit.Domain.Models.OrgOrganization", "Organization")
                        .WithMany("ExpCategories")
                        .HasForeignKey("OrganizationId")
                        .IsRequired()
                        .HasConstraintName("FK__EXP_Categ__Organ__1DB06A4F");

                    b.HasOne("Reimbit.Domain.Models.ProjProject", "Project")
                        .WithMany("ExpCategories")
                        .HasForeignKey("ProjectId")
                        .IsRequired()
                        .HasConstraintName("FK__EXP_Categ__Proje__1EA48E88");

                    b.Navigation("CreatedByUser");

                    b.Navigation("ModifiedByUser");

                    b.Navigation("Organization");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Reimbit.Domain.Models.ExpExpense", b =>
                {
                    b.HasOne("Reimbit.Domain.Models.ExpCategory", "Category")
                        .WithMany("ExpExpenses")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK__EXP_Expen__Categ__2EDAF651");

                    b.HasOne("Reimbit.Domain.Models.SecUser", "CreatedByUser")
                        .WithMany("ExpExpenseCreatedByUsers")
                        .HasForeignKey("CreatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK__EXP_Expen__Creat__31B762FC");

                    b.HasOne("Reimbit.Domain.Models.SecUser", "ModifiedByUser")
                        .WithMany("ExpExpenseModifiedByUsers")
                        .HasForeignKey("ModifiedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK__EXP_Expen__Modif__32AB8735");

                    b.HasOne("Reimbit.Domain.Models.OrgOrganization", "Organization")
                        .WithMany("ExpExpenses")
                        .HasForeignKey("OrganizationId")
                        .IsRequired()
                        .HasConstraintName("FK__EXP_Expen__Organ__2BFE89A6");

                    b.HasOne("Reimbit.Domain.Models.ProjProject", "Project")
                        .WithMany("ExpExpenses")
                        .HasForeignKey("ProjectId")
                        .IsRequired()
                        .HasConstraintName("FK__EXP_Expen__Proje__2DE6D218");

                    b.HasOne("Reimbit.Domain.Models.SecUser", "User")
                        .WithMany("ExpExpenseUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__EXP_Expen__UserI__2CF2ADDF");

                    b.Navigation("Category");

                    b.Navigation("CreatedByUser");

                    b.Navigation("ModifiedByUser");

                    b.Navigation("Organization");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Reimbit.Domain.Models.ExpReport", b =>
                {
                    b.HasOne("Reimbit.Domain.Models.SecUser", "CreatedByUser")
                        .WithMany("ExpReportCreatedByUsers")
                        .HasForeignKey("CreatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK__EXP_Repor__Creat__45BE5BA9");

                    b.HasOne("Reimbit.Domain.Models.SecUser", "Manager")
                        .WithMany("ExpReportManagers")
                        .HasForeignKey("ManagerId")
                        .IsRequired()
                        .HasConstraintName("FK__EXP_Repor__Manag__40F9A68C");

                    b.HasOne("Reimbit.Domain.Models.SecUser", "ModifiedByUser")
                        .WithMany("ExpReportModifiedByUsers")
                        .HasForeignKey("ModifiedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK__EXP_Repor__Modif__46B27FE2");

                    b.HasOne("Reimbit.Domain.Models.OrgOrganization", "Organization")
                        .WithMany("ExpReports")
                        .HasForeignKey("OrganizationId")
                        .IsRequired()
                        .HasConstraintName("FK__EXP_Repor__Organ__40058253");

                    b.HasOne("Reimbit.Domain.Models.ProjProject", "Project")
                        .WithMany("ExpReports")
                        .HasForeignKey("ProjectId")
                        .IsRequired()
                        .HasConstraintName("FK__EXP_Repor__Proje__41EDCAC5");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Manager");

                    b.Navigation("ModifiedByUser");

                    b.Navigation("Organization");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Reimbit.Domain.Models.OrgOrganization", b =>
                {
                    b.HasOne("Reimbit.Domain.Models.SecUser", "CreatedByUser")
                        .WithMany("OrgOrganizationCreatedByUsers")
                        .HasForeignKey("CreatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK__ORG_Organ__Creat__6A30C649");

                    b.HasOne("Reimbit.Domain.Models.SecUser", "ModifiedByUser")
                        .WithMany("OrgOrganizationModifiedByUsers")
                        .HasForeignKey("ModifiedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK__ORG_Organ__Modif__6B24EA82");

                    b.Navigation("CreatedByUser");

                    b.Navigation("ModifiedByUser");
                });

            modelBuilder.Entity("Reimbit.Domain.Models.ProjExpensePolicy", b =>
                {
                    b.HasOne("Reimbit.Domain.Models.ExpCategory", "Category")
                        .WithMany("ProjExpensePolicies")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK__PROJ_Expe__Categ__2739D489");

                    b.HasOne("Reimbit.Domain.Models.ProjProject", "Project")
                        .WithMany("ProjExpensePolicies")
                        .HasForeignKey("ProjectId")
                        .IsRequired()
                        .HasConstraintName("FK__PROJ_Expe__Proje__2645B050");

                    b.Navigation("Category");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Reimbit.Domain.Models.ProjProject", b =>
                {
                    b.HasOne("Reimbit.Domain.Models.SecUser", "CreatedByUser")
                        .WithMany("ProjProjectCreatedByUsers")
                        .HasForeignKey("CreatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK__PROJ_Proj__Creat__0E6E26BF");

                    b.HasOne("Reimbit.Domain.Models.SecUser", "Manager")
                        .WithMany("ProjProjectManagers")
                        .HasForeignKey("ManagerId")
                        .IsRequired()
                        .HasConstraintName("FK__PROJ_Proj__Manag__0D7A0286");

                    b.HasOne("Reimbit.Domain.Models.SecUser", "ModifiedByUser")
                        .WithMany("ProjProjectModifiedByUsers")
                        .HasForeignKey("ModifiedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK__PROJ_Proj__Modif__0F624AF8");

                    b.HasOne("Reimbit.Domain.Models.OrgOrganization", "Organization")
                        .WithMany("ProjProjects")
                        .HasForeignKey("OrganizationId")
                        .IsRequired()
                        .HasConstraintName("FK__PROJ_Proj__Organ__0C85DE4D");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Manager");

                    b.Navigation("ModifiedByUser");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Reimbit.Domain.Models.ProjProjectMember", b =>
                {
                    b.HasOne("Reimbit.Domain.Models.OrgOrganization", "Organization")
                        .WithMany("ProjProjectMembers")
                        .HasForeignKey("OrganizationId")
                        .IsRequired()
                        .HasConstraintName("FK__PROJ_Proj__Organ__17036CC0");

                    b.HasOne("Reimbit.Domain.Models.ProjProject", "Project")
                        .WithMany("ProjProjectMembers")
                        .HasForeignKey("ProjectId")
                        .IsRequired()
                        .HasConstraintName("FK__PROJ_Proj__Proje__160F4887");

                    b.HasOne("Reimbit.Domain.Models.SecUser", "User")
                        .WithMany("ProjProjectMembers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__PROJ_Proj__UserI__17F790F9");

                    b.Navigation("Organization");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Reimbit.Domain.Models.SecRole", b =>
                {
                    b.HasOne("Reimbit.Domain.Models.SecUser", "CreatedByUser")
                        .WithMany("SecRoleCreatedByUsers")
                        .HasForeignKey("CreatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK__SEC_Role__Create__778AC167");

                    b.HasOne("Reimbit.Domain.Models.SecUser", "ModifiedByUser")
                        .WithMany("SecRoleModifiedByUsers")
                        .HasForeignKey("ModifiedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK__SEC_Role__Modifi__787EE5A0");

                    b.HasOne("Reimbit.Domain.Models.OrgOrganization", "Organization")
                        .WithMany("SecRoles")
                        .HasForeignKey("OrganizationId")
                        .HasConstraintName("FK__SEC_Role__Organi__76969D2E");

                    b.Navigation("CreatedByUser");

                    b.Navigation("ModifiedByUser");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Reimbit.Domain.Models.SecRoleClaim", b =>
                {
                    b.HasOne("Reimbit.Domain.Models.SecUser", "CreatedByUser")
                        .WithMany("SecRoleClaimCreatedByUsers")
                        .HasForeignKey("CreatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK__SEC_RoleC__Creat__7D439ABD");

                    b.HasOne("Reimbit.Domain.Models.SecUser", "ModifiedByUser")
                        .WithMany("SecRoleClaimModifiedByUsers")
                        .HasForeignKey("ModifiedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK__SEC_RoleC__Modif__7E37BEF6");

                    b.HasOne("Reimbit.Domain.Models.SecRole", "Role")
                        .WithMany("SecRoleClaims")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK__SEC_RoleC__RoleI__7C4F7684");

                    b.Navigation("CreatedByUser");

                    b.Navigation("ModifiedByUser");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Reimbit.Domain.Models.SecUser", b =>
                {
                    b.HasOne("Reimbit.Domain.Models.SecUser", "CreatedByUser")
                        .WithMany("InverseCreatedByUser")
                        .HasForeignKey("CreatedByUserId")
                        .HasConstraintName("FK__SEC_User__Create__628FA481");

                    b.HasOne("Reimbit.Domain.Models.SecUser", "ModifiedByUser")
                        .WithMany("InverseModifiedByUser")
                        .HasForeignKey("ModifiedByUserId")
                        .HasConstraintName("FK__SEC_User__Modifi__6383C8BA");

                    b.Navigation("CreatedByUser");

                    b.Navigation("ModifiedByUser");
                });

            modelBuilder.Entity("Reimbit.Domain.Models.SecUserAuth", b =>
                {
                    b.HasOne("Reimbit.Domain.Models.OrgOrganization", "Organization")
                        .WithMany("SecUserAuth")
                        .HasForeignKey("OrganizationId")
                        .IsRequired()
                        .HasConstraintName("FK__SEC_UserA__Organ__607251E5");

                    b.HasOne("Reimbit.Domain.Models.SecUser", "User")
                        .WithOne("SecUserAuth")
                        .HasForeignKey("Reimbit.Domain.Models.SecUserAuth", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK__SEC_UserA__UserI__70DDC3D8");

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Reimbit.Domain.Models.SecUserRole", b =>
                {
                    b.HasOne("Reimbit.Domain.Models.SecUser", "CreatedByUser")
                        .WithMany("SecUserRoleCreatedByUsers")
                        .HasForeignKey("CreatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK__SEC_UserR__Creat__04E4BC85");

                    b.HasOne("Reimbit.Domain.Models.SecUser", "ModifiedByUser")
                        .WithMany("SecUserRoleModifiedByUsers")
                        .HasForeignKey("ModifiedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK__SEC_UserR__Modif__05D8E0BE");

                    b.HasOne("Reimbit.Domain.Models.SecUser", "User")
                        .WithMany("SecUserRoleUsers")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__SEC_UserR__UserI__03F0984C");

                    b.Navigation("CreatedByUser");

                    b.Navigation("ModifiedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Reimbit.Domain.Models.ExpCategory", b =>
                {
                    b.Navigation("ExpExpenses");

                    b.Navigation("ProjExpensePolicies");
                });

            modelBuilder.Entity("Reimbit.Domain.Models.ExpExpense", b =>
                {
                    b.Navigation("ComExpenseQueries");
                });

            modelBuilder.Entity("Reimbit.Domain.Models.OrgOrganization", b =>
                {
                    b.Navigation("ExpCategories");

                    b.Navigation("ExpExpenses");

                    b.Navigation("ExpReports");

                    b.Navigation("ProjProjectMembers");

                    b.Navigation("ProjProjects");

                    b.Navigation("SecRoles");

                    b.Navigation("SecUserAuth");
                });

            modelBuilder.Entity("Reimbit.Domain.Models.ProjProject", b =>
                {
                    b.Navigation("ExpCategories");

                    b.Navigation("ExpExpenses");

                    b.Navigation("ExpReports");

                    b.Navigation("ProjExpensePolicies");

                    b.Navigation("ProjProjectMembers");
                });

            modelBuilder.Entity("Reimbit.Domain.Models.SecRole", b =>
                {
                    b.Navigation("SecRoleClaims");
                });

            modelBuilder.Entity("Reimbit.Domain.Models.SecUser", b =>
                {
                    b.Navigation("ComExpenseQueries");

                    b.Navigation("ExpCategoryCreatedByUsers");

                    b.Navigation("ExpCategoryModifiedByUsers");

                    b.Navigation("ExpExpenseCreatedByUsers");

                    b.Navigation("ExpExpenseModifiedByUsers");

                    b.Navigation("ExpExpenseUsers");

                    b.Navigation("ExpReportCreatedByUsers");

                    b.Navigation("ExpReportManagers");

                    b.Navigation("ExpReportModifiedByUsers");

                    b.Navigation("InverseCreatedByUser");

                    b.Navigation("InverseModifiedByUser");

                    b.Navigation("OrgOrganizationCreatedByUsers");

                    b.Navigation("OrgOrganizationModifiedByUsers");

                    b.Navigation("ProjProjectCreatedByUsers");

                    b.Navigation("ProjProjectManagers");

                    b.Navigation("ProjProjectMembers");

                    b.Navigation("ProjProjectModifiedByUsers");

                    b.Navigation("SecRoleClaimCreatedByUsers");

                    b.Navigation("SecRoleClaimModifiedByUsers");

                    b.Navigation("SecRoleCreatedByUsers");

                    b.Navigation("SecRoleModifiedByUsers");

                    b.Navigation("SecUserAuth");

                    b.Navigation("SecUserRoleCreatedByUsers");

                    b.Navigation("SecUserRoleModifiedByUsers");

                    b.Navigation("SecUserRoleUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
